# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-07 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='email',
            field=models.EmailField(default='SOME STRING', max_length=100),
        ),
    ]
